### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by slotherinee** [typicalninja/google-sr#13]
**What package is this bug report for?**

[ google-sr dependency ]

**Describe the bug**
When i try to npm install google-sr logs an error and i see this:

npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^

**Expected behavior**
Download of a package

**Environment (please complete the following information):**
 - Platform with version: Nodejs v20.14.0, npm v10.7.0

**Additional context**
Works with yarn, doesnt work with npm.

**Comment by typicalninja** [comment]
Ill take look. pnpm should change it when publishing. seems like it didn't for some reason

**Comment by typicalninja** [comment]
Please try installing google-sr@3.3.1
