### ISSUE TITLE
Change/hide location from google search

### ISSUE THREAD

**Issue by mokendkomer** [typicalninja/google-sr#34]
**Is your feature request related to a problem? Please describe.**
No it isn't

**What package is this feature request for?**
the google-sr NPM package

**Describe the solution you'd like**
Currently, I'm receiving a lot of location-specific results. I'd like for there to be an option to remove my location from the search entirely, and get results that are relevant globally.

**Describe alternatives you've considered**
I tried setting a 'gl' param with no luck. I haven't tried many solutions yet though.

**Additional context**
Thanks for building this package! I think you did a great job and I hope this suggestion isn't a burden to implement.

**Comment by typicalninja** [comment]
can you give me a specific query that your using to get this result.

the issue is its entirely upto google on what results are to be returned. unless you use a proxy or something i dont see how we can fix this.

**Comment by typicalninja** [comment]
okay i did some tests and saw that adding the 'gl' is working as expected (without proxies). can you provide a small code sample on how you added the param?

**Comment by mokendkomer** [comment]
Thanks for taking the time to look into it!

I used some query like 'best coffee shop', which admittedly is useless without geolocation. I was just hoping to find a way to search with as little bias as possible.

Maybe consider adding the gl param to search()'s options, so it's a little easier to set?

**Comment by typicalninja** [comment]
> I used some query like 'best coffee shop', 

lol that is the same query i used for my test.

the use case seems too specific to add the gl param as a option, since the main reason for requestOptions is to facilitate this

**Comment by mokendkomer** [comment]
nice lol that's a wild coincidence

Yeah a top-level param option is what I meant, sorry for the !articulate.
